---
- name: Configure Kali Linux VM
  hosts: kali-lbox
  become: yes
  tasks:
    - name: Print message
      command: echo -e "\nYou have selected 'set-terminal'\n"

    - name: Display completion message
      debug:
        msg: "Display completion message."

    - name: Install nmcli
      apt:
        name: network-manager
        state: present
